
* Nome do Software (ou Biblioteca):
- SIMULADOR DE PROPRIEDADES TERMODINÂMICAS DE SUBSTÂNCIAS
PURAS A PARTIR DE DENSIDADE E TEMPERATURA

* Resumo e/ou informação extra: 
- A correta previsão das propriedades termodinâmicas e cálculo do equilíbrio de fases constitui-se num
ponto fundamental do projeto de qualquer processo da industria química, como sistemas de refrigeração.
A exploração e produção de reservas naturais de hidrocarbonetos não foge a essa regra, com a dificuldade
adicional de tratar complexas misturas de hidrocarbonetos, muitas vezes não bem caracterizadas, além
da presença de compostos não orgânicos, como água e dióxido de carbono, empregados em técnicas para
aumentar o fator de recuperação das jazidas.
Na simulação numérica computacional, que usa o modelo composicional de reservatórios de hidro-
carbonetos, um dos conjuntos de equações utilizado para a solução é composto pelos coeficientes de
distribuição dos componentes entre as fases presentes no meio poroso. Em varios momentos da simulação
uma ou mais fases podem ser constituídas de compostos puros. Nesse caso, ao invés de utilizar equações
de estado, são utilizadas correlações para prever as propriedades termodinâmicas, bem como as suas
derivadas (necessárias para o cálculo do jacobiano do método de Newton).

Objetivo geral:
– Deselvolver um software que calcula as propriedades termodinâmicas de uma substância pura
a partir de equações experimentais.

* Versão: 
- 1.0.

* Data:
- 2014/2 - segundo semestre.
  
* Autor de Contato:
- André Duarte Bueno <andreduartebueno@gmail.com>

* Lista dos Autores:
- THÔMAS AUGUSTO STEMPKOWSKI MENEGAZZO
- ADOLFO PUIME PIRES (TERMODINÂMICA)
- André Duarte Bueno <andreduartebueno@gmail.com>

* Áreas de pesquisa vinculadas: 
- Modelagem Matemática Computacional
- Engenharia Reservatório
- Engenharia Química
- Termodinâmica
  

* Vinculo com: 
- Trabalho da disciplina de programação prática.

* Paradigmas: 
- POO - Programação Orientada a Objeto (códigos em C++)

* Tipo de Interface: 
- Terminal e gráfica (gnuplot).

* Plataformas Suportadas: 
- Windows e GNU/Linux e Mac OS X (não testada).

* Linguagens Utilizadas: 
- C++ 11.

* Bibliotecas Utilizadas (dependências):
- QT

* Softwares utilizados (dependências)
- QT

* Tipo de Licença:
- GPL
- Entre em contato com o Prof. André Duarte Bueno
  andreduartebueno@gmail.com
  para que o mesmo gere um novo projeto no github do ldsc para que você (e sua equipe) possam trabalhar na nova versão.
- Se este projeto tem como número de versão 1.0 a nova versão deverá ser 2.0 e assim sucessivamente.
- Os nomes dos autores originais deve ser preservada na nova versão, ou seja, adicione a informação do número da versão, os nomes dos membros da nova equipe, mas jamais apague os nomes dos autores originais (isto seria plágio).
- Na descrição do projeto informe que trata-se de uma nova versão, que tem como base a versão anterior e DESTAQUE COM CLAREZA E OBJETIVIDADE QUAIS AS NOVIDADES DA NOVA VERSÃO.
  
* Links:

